### ISSUE TITLE
Sintesis

### ISSUE THREAD

**Issue by bg55-a** [SistemasTecTlaxiaco/actividad-3-sintesis-bg55-a#2]
[Sintesis de Elementos importantes de la gestión de proyectos de software.pdf](https://github.com/SistemasTecTlaxiaco/actividad-3-sintesis-bg55-a/files/9463903/Sintesis.de.Elementos.importantes.de.la.gestion.de.proyectos.de.software.pdf)

**Comment by AndreLuna6** [comment]
Calificación 20%

**Comment by josealfredo79** [comment]
Checar las buenas practicas de la gestion de proyectos como una buena sintesis

**Comment by bg55-a** [comment]
[Sintesis.-.Gestion.de.proyectos.de.software.pdf](https://github.com/SistemasTecTlaxiaco/actividad-3-sintesis-bg55-a/files/9490161/Sintesis.-.Gestion.de.proyectos.de.software.pdf)

**Comment by josealfredo79** [comment]
Bien hecho y reviado
