### ISSUE TITLE
Sintesis

### ISSUE THREAD

**Issue by bg55-a** [SistemasTecTlaxiaco/actividad-3-sintesis-bg55-a#3]
[Sintesis de Buenas prácticas en gestión de proyectos.pdf](https://github.com/SistemasTecTlaxiaco/actividad-3-sintesis-bg55-a/files/12516432/Sintesis.de.Buenas.practicas.en.gestion.de.proyectos.pdf)

**Comment by JoseABCruz** [comment]
Calificación: 20%

**Comment by josealfredo79** [comment]
Bien hecho y revisado..
